services:
  - type: web
    name: hotelhalo-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/rooms
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
